# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app_name".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  app_name:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        stage: production
      target: app_name
    command: ["run-app_name"]
    container_name: app_name
    entrypoint: ["/docker/entrypoint.sh"]
    # env_file: .env.dev
    environment:
      ENV: prod
    image: app_name:latest
    stdin_open: true
    tty: true
    working_dir: /app/app_name

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        stage: development
      target: dev
    command: ["run-dev"]
    entrypoint: ["/docker/entrypoint.sh"]
    environment:
      ENV: dev
    image: app_name:dev
    stdin_open: true
    tty: true
    volumes:
      - ./:/app/app_name
    working_dir: /app/app_name
